# Generated by Django 5.0.1 on 2024-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nombre_ejercicio_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
