# Generated by Django 5.0.1 on 2024-02-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_rutina_dia_semana'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaSemana',
        ),
    ]
